config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    collection do
      get 'search_actor', to: 'movies#search_actor'  # Define a custom route for searching actors
    end
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews
    
    def average_rating
      reviews.average(:stars).to_f
    end
  end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
      @movies = Movie.includes(:reviews)
                     .group(:id)
                     .order(average_rating: :desc)
    end
  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssignmentSub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Movie List</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Year</th>
      <th>Director</th>
      <th>Filming Location</th>
      <th>Country</th>
      <th>Average Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.description %></td>
        <td><%= movie.year %></td>
        <td><%= movie.director %></td>
        <td><%= movie.filming_location %></td>
        <td><%= movie.country %></td>
        <td><%= movie.average_rating %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- Add a form for searching actors -->
<h2>Search for Actor</h2>
<%= form_with(url: search_actor_movies_path, method: :get) do |f| %>
  <%= f.label :name, 'Actor Name' %>
  <%= f.text_field :name %>
  <%= f.submit 'Search' %>
<% end %>